on:
  push:
    branches:
      - dev

name: Build Snapshot Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: HelloWorld.jar
          path: ${{ github.workspace }}/